from tkinter import *
window=Tk()
window.title("information")
window.geometry("300x200")
window.minsize(100,100)
# window.iconbitmap()
window.config(background="grey")
# label=Label(window, text="Hello World")
# label.pack()
label_title=Label(window, text="Bonjour python", font=("courrier",20), bg="grey", fg="white")
label_title.pack()
button=Button(window, text="Fermer", command=window.quit)
button.pack()
window.mainloop()
